/* UIBuilder.c generated by valac 0.18.1, the Vala compiler
 * generated from UIBuilder.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define TYPE_UI_BUILDER (ui_builder_get_type ())
#define UI_BUILDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_UI_BUILDER, UIBuilder))
#define UI_BUILDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_UI_BUILDER, UIBuilderClass))
#define IS_UI_BUILDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_UI_BUILDER))
#define IS_UI_BUILDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_UI_BUILDER))
#define UI_BUILDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_UI_BUILDER, UIBuilderClass))

typedef struct _UIBuilder UIBuilder;
typedef struct _UIBuilderClass UIBuilderClass;
typedef struct _UIBuilderPrivate UIBuilderPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _ParamSpecUIBuilder ParamSpecUIBuilder;

struct _UIBuilder {
	GTypeInstance parent_instance;
	volatile int ref_count;
	UIBuilderPrivate * priv;
};

struct _UIBuilderClass {
	GTypeClass parent_class;
	void (*finalize) (UIBuilder *self);
};

struct _UIBuilderPrivate {
	GtkBuilder* builder;
};

struct _ParamSpecUIBuilder {
	GParamSpec parent_instance;
};


static gpointer ui_builder_parent_class = NULL;

gpointer ui_builder_ref (gpointer instance);
void ui_builder_unref (gpointer instance);
GParamSpec* param_spec_ui_builder (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_ui_builder (GValue* value, gpointer v_object);
void value_take_ui_builder (GValue* value, gpointer v_object);
gpointer value_get_ui_builder (const GValue* value);
GType ui_builder_get_type (void) G_GNUC_CONST;
#define UI_BUILDER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_UI_BUILDER, UIBuilderPrivate))
enum  {
	UI_BUILDER_DUMMY_PROPERTY
};
UIBuilder* ui_builder_new (const gchar* path);
UIBuilder* ui_builder_construct (GType object_type, const gchar* path);
GtkButton* ui_builder_get_button (UIBuilder* self, const gchar* name);
GtkWindow* ui_builder_get_window (UIBuilder* self, const gchar* name);
GtkLabel* ui_builder_get_label (UIBuilder* self, const gchar* name);
GtkImage* ui_builder_get_image (UIBuilder* self, const gchar* name);
GtkBox* ui_builder_get_box (UIBuilder* self, const gchar* name);
GtkToggleButton* ui_builder_get_toggle (UIBuilder* self, const gchar* name);
static void ui_builder_finalize (UIBuilder* obj);


UIBuilder* ui_builder_construct (GType object_type, const gchar* path) {
	UIBuilder* self = NULL;
	GError * _inner_error_ = NULL;
#line 10 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	g_return_val_if_fail (path != NULL, NULL);
#line 10 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	self = (UIBuilder*) g_type_create_instance (object_type);
#line 79 "UIBuilder.c"
	{
		GtkBuilder* _tmp0_;
		const gchar* _tmp1_;
#line 12 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		_tmp0_ = self->priv->builder;
#line 12 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		_tmp1_ = path;
#line 12 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		gtk_builder_add_from_file (_tmp0_, _tmp1_, &_inner_error_);
#line 12 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		if (_inner_error_ != NULL) {
#line 91 "UIBuilder.c"
			goto __catch53_g_error;
		}
	}
	goto __finally53;
	__catch53_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp2_;
		GError* _tmp3_;
		const gchar* _tmp4_;
#line 11 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		e = _inner_error_;
#line 11 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		_inner_error_ = NULL;
#line 14 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		_tmp2_ = path;
#line 14 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		_tmp3_ = e;
#line 14 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		_tmp4_ = _tmp3_->message;
#line 14 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		g_critical ("UIBuilder.vala:14: Loading %s: %s", _tmp2_, _tmp4_);
#line 11 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		_g_error_free0 (e);
#line 116 "UIBuilder.c"
	}
	__finally53:
#line 11 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	if (_inner_error_ != NULL) {
#line 11 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 11 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		g_clear_error (&_inner_error_);
#line 11 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		return NULL;
#line 127 "UIBuilder.c"
	}
#line 10 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	return self;
#line 131 "UIBuilder.c"
}


UIBuilder* ui_builder_new (const gchar* path) {
#line 10 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	return ui_builder_construct (TYPE_UI_BUILDER, path);
#line 138 "UIBuilder.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 19 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	return self ? g_object_ref (self) : NULL;
#line 145 "UIBuilder.c"
}


GtkButton* ui_builder_get_button (UIBuilder* self, const gchar* name) {
	GtkButton* result = NULL;
	GtkBuilder* _tmp0_;
	const gchar* _tmp1_;
	GObject* _tmp2_ = NULL;
	GtkButton* _tmp3_;
#line 18 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	g_return_val_if_fail (IS_UI_BUILDER (self), NULL);
#line 18 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 19 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp0_ = self->priv->builder;
#line 19 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp1_ = name;
#line 19 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp2_ = gtk_builder_get_object (_tmp0_, _tmp1_);
#line 19 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp3_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp2_, GTK_TYPE_BUTTON) ? ((GtkButton*) _tmp2_) : NULL);
#line 19 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	result = _tmp3_;
#line 19 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	return result;
#line 171 "UIBuilder.c"
}


GtkWindow* ui_builder_get_window (UIBuilder* self, const gchar* name) {
	GtkWindow* result = NULL;
	GtkBuilder* _tmp0_;
	const gchar* _tmp1_;
	GObject* _tmp2_ = NULL;
	GtkWindow* _tmp3_;
#line 22 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	g_return_val_if_fail (IS_UI_BUILDER (self), NULL);
#line 22 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 23 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp0_ = self->priv->builder;
#line 23 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp1_ = name;
#line 23 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp2_ = gtk_builder_get_object (_tmp0_, _tmp1_);
#line 23 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp3_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp2_, GTK_TYPE_WINDOW) ? ((GtkWindow*) _tmp2_) : NULL);
#line 23 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	result = _tmp3_;
#line 23 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	return result;
#line 197 "UIBuilder.c"
}


GtkLabel* ui_builder_get_label (UIBuilder* self, const gchar* name) {
	GtkLabel* result = NULL;
	GtkBuilder* _tmp0_;
	const gchar* _tmp1_;
	GObject* _tmp2_ = NULL;
	GtkLabel* _tmp3_;
#line 26 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	g_return_val_if_fail (IS_UI_BUILDER (self), NULL);
#line 26 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp0_ = self->priv->builder;
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp1_ = name;
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp2_ = gtk_builder_get_object (_tmp0_, _tmp1_);
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp3_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp2_, GTK_TYPE_LABEL) ? ((GtkLabel*) _tmp2_) : NULL);
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	result = _tmp3_;
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	return result;
#line 223 "UIBuilder.c"
}


GtkImage* ui_builder_get_image (UIBuilder* self, const gchar* name) {
	GtkImage* result = NULL;
	GtkBuilder* _tmp0_;
	const gchar* _tmp1_;
	GObject* _tmp2_ = NULL;
	GtkImage* _tmp3_;
#line 30 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	g_return_val_if_fail (IS_UI_BUILDER (self), NULL);
#line 30 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 31 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp0_ = self->priv->builder;
#line 31 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp1_ = name;
#line 31 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp2_ = gtk_builder_get_object (_tmp0_, _tmp1_);
#line 31 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp3_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp2_, GTK_TYPE_IMAGE) ? ((GtkImage*) _tmp2_) : NULL);
#line 31 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	result = _tmp3_;
#line 31 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	return result;
#line 249 "UIBuilder.c"
}


GtkBox* ui_builder_get_box (UIBuilder* self, const gchar* name) {
	GtkBox* result = NULL;
	GtkBuilder* _tmp0_;
	const gchar* _tmp1_;
	GObject* _tmp2_ = NULL;
	GtkBox* _tmp3_;
#line 34 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	g_return_val_if_fail (IS_UI_BUILDER (self), NULL);
#line 34 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 35 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp0_ = self->priv->builder;
#line 35 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp1_ = name;
#line 35 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp2_ = gtk_builder_get_object (_tmp0_, _tmp1_);
#line 35 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp3_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp2_, GTK_TYPE_BOX) ? ((GtkBox*) _tmp2_) : NULL);
#line 35 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	result = _tmp3_;
#line 35 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	return result;
#line 275 "UIBuilder.c"
}


GtkToggleButton* ui_builder_get_toggle (UIBuilder* self, const gchar* name) {
	GtkToggleButton* result = NULL;
	GtkBuilder* _tmp0_;
	const gchar* _tmp1_;
	GObject* _tmp2_ = NULL;
	GtkToggleButton* _tmp3_;
#line 38 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	g_return_val_if_fail (IS_UI_BUILDER (self), NULL);
#line 38 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 39 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp0_ = self->priv->builder;
#line 39 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp1_ = name;
#line 39 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp2_ = gtk_builder_get_object (_tmp0_, _tmp1_);
#line 39 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp3_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp2_, GTK_TYPE_TOGGLE_BUTTON) ? ((GtkToggleButton*) _tmp2_) : NULL);
#line 39 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	result = _tmp3_;
#line 39 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	return result;
#line 301 "UIBuilder.c"
}


static void value_ui_builder_init (GValue* value) {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	value->data[0].v_pointer = NULL;
#line 308 "UIBuilder.c"
}


static void value_ui_builder_free_value (GValue* value) {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	if (value->data[0].v_pointer) {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		ui_builder_unref (value->data[0].v_pointer);
#line 317 "UIBuilder.c"
	}
}


static void value_ui_builder_copy_value (const GValue* src_value, GValue* dest_value) {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	if (src_value->data[0].v_pointer) {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		dest_value->data[0].v_pointer = ui_builder_ref (src_value->data[0].v_pointer);
#line 327 "UIBuilder.c"
	} else {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		dest_value->data[0].v_pointer = NULL;
#line 331 "UIBuilder.c"
	}
}


static gpointer value_ui_builder_peek_pointer (const GValue* value) {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	return value->data[0].v_pointer;
#line 339 "UIBuilder.c"
}


static gchar* value_ui_builder_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	if (collect_values[0].v_pointer) {
#line 346 "UIBuilder.c"
		UIBuilder* object;
		object = collect_values[0].v_pointer;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		if (object->parent_instance.g_class == NULL) {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 353 "UIBuilder.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 357 "UIBuilder.c"
		}
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		value->data[0].v_pointer = ui_builder_ref (object);
#line 361 "UIBuilder.c"
	} else {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		value->data[0].v_pointer = NULL;
#line 365 "UIBuilder.c"
	}
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	return NULL;
#line 369 "UIBuilder.c"
}


static gchar* value_ui_builder_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	UIBuilder** object_p;
	object_p = collect_values[0].v_pointer;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	if (!object_p) {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 380 "UIBuilder.c"
	}
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	if (!value->data[0].v_pointer) {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		*object_p = NULL;
#line 386 "UIBuilder.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		*object_p = value->data[0].v_pointer;
#line 390 "UIBuilder.c"
	} else {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		*object_p = ui_builder_ref (value->data[0].v_pointer);
#line 394 "UIBuilder.c"
	}
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	return NULL;
#line 398 "UIBuilder.c"
}


GParamSpec* param_spec_ui_builder (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecUIBuilder* spec;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_UI_BUILDER), NULL);
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	return G_PARAM_SPEC (spec);
#line 412 "UIBuilder.c"
}


gpointer value_get_ui_builder (const GValue* value) {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_UI_BUILDER), NULL);
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	return value->data[0].v_pointer;
#line 421 "UIBuilder.c"
}


void value_set_ui_builder (GValue* value, gpointer v_object) {
	UIBuilder* old;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_UI_BUILDER));
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	old = value->data[0].v_pointer;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	if (v_object) {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_UI_BUILDER));
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		value->data[0].v_pointer = v_object;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		ui_builder_ref (value->data[0].v_pointer);
#line 441 "UIBuilder.c"
	} else {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		value->data[0].v_pointer = NULL;
#line 445 "UIBuilder.c"
	}
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	if (old) {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		ui_builder_unref (old);
#line 451 "UIBuilder.c"
	}
}


void value_take_ui_builder (GValue* value, gpointer v_object) {
	UIBuilder* old;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_UI_BUILDER));
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	old = value->data[0].v_pointer;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	if (v_object) {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_UI_BUILDER));
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		value->data[0].v_pointer = v_object;
#line 470 "UIBuilder.c"
	} else {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		value->data[0].v_pointer = NULL;
#line 474 "UIBuilder.c"
	}
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	if (old) {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		ui_builder_unref (old);
#line 480 "UIBuilder.c"
	}
}


static void ui_builder_class_init (UIBuilderClass * klass) {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	ui_builder_parent_class = g_type_class_peek_parent (klass);
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	UI_BUILDER_CLASS (klass)->finalize = ui_builder_finalize;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	g_type_class_add_private (klass, sizeof (UIBuilderPrivate));
#line 492 "UIBuilder.c"
}


static void ui_builder_instance_init (UIBuilder * self) {
	GtkBuilder* _tmp0_;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	self->priv = UI_BUILDER_GET_PRIVATE (self);
#line 7 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_tmp0_ = gtk_builder_new ();
#line 7 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	self->priv->builder = _tmp0_;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	self->ref_count = 1;
#line 506 "UIBuilder.c"
}


static void ui_builder_finalize (UIBuilder* obj) {
	UIBuilder * self;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_UI_BUILDER, UIBuilder);
#line 7 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	_g_object_unref0 (self->priv->builder);
#line 516 "UIBuilder.c"
}


GType ui_builder_get_type (void) {
	static volatile gsize ui_builder_type_id__volatile = 0;
	if (g_once_init_enter (&ui_builder_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_ui_builder_init, value_ui_builder_free_value, value_ui_builder_copy_value, value_ui_builder_peek_pointer, "p", value_ui_builder_collect_value, "p", value_ui_builder_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (UIBuilderClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ui_builder_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UIBuilder), 0, (GInstanceInitFunc) ui_builder_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType ui_builder_type_id;
		ui_builder_type_id = g_type_register_fundamental (g_type_fundamental_next (), "UIBuilder", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&ui_builder_type_id__volatile, ui_builder_type_id);
	}
	return ui_builder_type_id__volatile;
}


gpointer ui_builder_ref (gpointer instance) {
	UIBuilder* self;
	self = instance;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	g_atomic_int_inc (&self->ref_count);
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	return instance;
#line 541 "UIBuilder.c"
}


void ui_builder_unref (gpointer instance) {
	UIBuilder* self;
	self = instance;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		UI_BUILDER_GET_CLASS (self)->finalize (self);
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/UIBuilder.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 554 "UIBuilder.c"
	}
}



