/* Utils.c generated by valac 0.18.1, the Vala compiler
 * generated from Utils.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <gtk/gtk.h>
#include <gobject/gvaluecollector.h>


#define TYPE_UTILS (utils_get_type ())
#define UTILS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_UTILS, Utils))
#define UTILS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_UTILS, UtilsClass))
#define IS_UTILS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_UTILS))
#define IS_UTILS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_UTILS))
#define UTILS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_UTILS, UtilsClass))

typedef struct _Utils Utils;
typedef struct _UtilsClass UtilsClass;
typedef struct _UtilsPrivate UtilsPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_time_zone_unref0(var) ((var == NULL) ? NULL : (var = (g_time_zone_unref (var), NULL)))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
typedef struct _Block18Data Block18Data;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _ParamSpecUtils ParamSpecUtils;

struct _Utils {
	GTypeInstance parent_instance;
	volatile int ref_count;
	UtilsPrivate * priv;
};

struct _UtilsClass {
	GTypeClass parent_class;
	void (*finalize) (Utils *self);
};

struct _Block18Data {
	int _ref_count_;
	GtkMessageDialog* dialog;
};

struct _ParamSpecUtils {
	GParamSpec parent_instance;
};


static gpointer utils_parent_class = NULL;
static gchar** utils_MONTHS;
static gint utils_MONTHS_length1;
static gchar** utils_MONTHS = NULL;
static gint utils_MONTHS_length1 = 0;
static gint _utils_MONTHS_size_ = 0;

gpointer utils_ref (gpointer instance);
void utils_unref (gpointer instance);
GParamSpec* param_spec_utils (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_utils (GValue* value, gpointer v_object);
void value_take_utils (GValue* value, gpointer v_object);
gpointer value_get_utils (const GValue* value);
GType utils_get_type (void) G_GNUC_CONST;
enum  {
	UTILS_DUMMY_PROPERTY
};
GDateTime* utils_parse_date (const gchar* input);
gchar* utils_get_time_delta (GDateTime* time, GDateTime* now);
gchar* utils_get_file_name (const gchar* path);
gchar* utils_get_file_type (const gchar* path);
gchar* utils_get_avatar_name (const gchar* path);
void utils_show_error_dialog (const gchar* message);
static Block18Data* block18_data_ref (Block18Data* _data18_);
static void block18_data_unref (void * _userdata_);
static void __lambda8_ (Block18Data* _data18_, gint id);
static void ___lambda8__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);
Utils* utils_new (void);
Utils* utils_construct (GType object_type);
static void utils_finalize (Utils* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


/**
* Parses a date given by Twitter in the form 'Wed Jun 20 19:01:28 +0000 2012'
* and creates a GLib.DateTime in the local time zone to work with.
*
* @return The given date as GLib.DateTime in the current time zone.
*/
static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* _tmp0_;
	glong _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* end;
	gchar* _tmp3_;
#line 1147 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	_tmp0_ = str;
#line 1147 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	_tmp1_ = maxlen;
#line 1147 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
#line 1147 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	end = _tmp2_;
#line 1148 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	_tmp3_ = end;
#line 1148 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	if (_tmp3_ == NULL) {
#line 114 "Utils.c"
		glong _tmp4_;
#line 1149 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		_tmp4_ = maxlen;
#line 1149 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		result = _tmp4_;
#line 1149 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		return result;
#line 122 "Utils.c"
	} else {
		gchar* _tmp5_;
		gchar* _tmp6_;
#line 1151 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		_tmp5_ = end;
#line 1151 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		_tmp6_ = str;
#line 1151 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		result = (glong) (_tmp5_ - _tmp6_);
#line 1151 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		return result;
#line 134 "Utils.c"
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_;
	gboolean _tmp3_;
	glong _tmp9_;
	glong _tmp15_;
	glong _tmp18_;
	glong _tmp19_;
	glong _tmp20_;
	glong _tmp21_;
	glong _tmp22_;
	gchar* _tmp23_ = NULL;
#line 1158 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1160 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	_tmp1_ = offset;
#line 1160 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	if (_tmp1_ >= ((glong) 0)) {
#line 159 "Utils.c"
		glong _tmp2_;
#line 1160 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		_tmp2_ = len;
#line 1160 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		_tmp0_ = _tmp2_ >= ((glong) 0);
#line 165 "Utils.c"
	} else {
#line 1160 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 169 "Utils.c"
	}
#line 1160 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	_tmp3_ = _tmp0_;
#line 1160 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	if (_tmp3_) {
#line 175 "Utils.c"
		glong _tmp4_;
		glong _tmp5_;
		glong _tmp6_ = 0L;
#line 1162 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		_tmp4_ = offset;
#line 1162 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		_tmp5_ = len;
#line 1162 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		_tmp6_ = string_strnlen ((gchar*) self, _tmp4_ + _tmp5_);
#line 1162 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		string_length = _tmp6_;
#line 187 "Utils.c"
	} else {
		gint _tmp7_;
		gint _tmp8_;
#line 1164 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		_tmp7_ = strlen (self);
#line 1164 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		_tmp8_ = _tmp7_;
#line 1164 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		string_length = (glong) _tmp8_;
#line 197 "Utils.c"
	}
#line 1167 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	_tmp9_ = offset;
#line 1167 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	if (_tmp9_ < ((glong) 0)) {
#line 203 "Utils.c"
		glong _tmp10_;
		glong _tmp11_;
		glong _tmp12_;
#line 1168 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		_tmp10_ = string_length;
#line 1168 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		_tmp11_ = offset;
#line 1168 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		offset = _tmp10_ + _tmp11_;
#line 1169 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		_tmp12_ = offset;
#line 1169 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		g_return_val_if_fail (_tmp12_ >= ((glong) 0), NULL);
#line 217 "Utils.c"
	} else {
		glong _tmp13_;
		glong _tmp14_;
#line 1171 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		_tmp13_ = offset;
#line 1171 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		_tmp14_ = string_length;
#line 1171 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		g_return_val_if_fail (_tmp13_ <= _tmp14_, NULL);
#line 227 "Utils.c"
	}
#line 1173 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	_tmp15_ = len;
#line 1173 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	if (_tmp15_ < ((glong) 0)) {
#line 233 "Utils.c"
		glong _tmp16_;
		glong _tmp17_;
#line 1174 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		_tmp16_ = string_length;
#line 1174 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		_tmp17_ = offset;
#line 1174 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		len = _tmp16_ - _tmp17_;
#line 242 "Utils.c"
	}
#line 1176 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	_tmp18_ = offset;
#line 1176 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	_tmp19_ = len;
#line 1176 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	_tmp20_ = string_length;
#line 1176 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	g_return_val_if_fail ((_tmp18_ + _tmp19_) <= _tmp20_, NULL);
#line 1177 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	_tmp21_ = offset;
#line 1177 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	_tmp22_ = len;
#line 1177 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	_tmp23_ = g_strndup (((gchar*) self) + _tmp21_, (gsize) _tmp22_);
#line 1177 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	result = _tmp23_;
#line 1177 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	return result;
#line 262 "Utils.c"
}


GDateTime* utils_parse_date (const gchar* input) {
	GDateTime* result = NULL;
	const gchar* _tmp0_;
	const gchar* _tmp2_;
	gchar* _tmp3_ = NULL;
	gchar* month_str;
	const gchar* _tmp4_;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_;
	gint _tmp7_ = 0;
	gint _tmp8_;
	gint day;
	const gchar* _tmp9_;
	const gchar* _tmp10_;
	gint _tmp11_;
	gint _tmp12_;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_;
	gint _tmp15_ = 0;
	gint _tmp16_;
	gint year;
	const gchar* _tmp17_;
	gchar* _tmp18_ = NULL;
	gchar* timezone;
	gint month;
	const gchar* _tmp19_;
	const gchar* _tmp20_;
	GQuark _tmp22_ = 0U;
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	static GQuark _tmp21_label0 = 0;
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	static GQuark _tmp21_label1 = 0;
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	static GQuark _tmp21_label2 = 0;
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	static GQuark _tmp21_label3 = 0;
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	static GQuark _tmp21_label4 = 0;
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	static GQuark _tmp21_label5 = 0;
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	static GQuark _tmp21_label6 = 0;
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	static GQuark _tmp21_label7 = 0;
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	static GQuark _tmp21_label8 = 0;
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	static GQuark _tmp21_label9 = 0;
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	static GQuark _tmp21_label10 = 0;
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	static GQuark _tmp21_label11 = 0;
#line 318 "Utils.c"
	const gchar* _tmp23_;
	gchar* _tmp24_ = NULL;
	gchar* _tmp25_;
	gint _tmp26_ = 0;
	gint _tmp27_;
	gint hour;
	const gchar* _tmp28_;
	gchar* _tmp29_ = NULL;
	gchar* _tmp30_;
	gint _tmp31_ = 0;
	gint _tmp32_;
	gint minute;
	const gchar* _tmp33_;
	gchar* _tmp34_ = NULL;
	gchar* _tmp35_;
	gint _tmp36_ = 0;
	gint _tmp37_;
	gint second;
	const gchar* _tmp38_;
	GTimeZone* _tmp39_;
	GTimeZone* _tmp40_;
	gint _tmp41_;
	gint _tmp42_;
	gint _tmp43_;
	gint _tmp44_;
	gint _tmp45_;
	gint _tmp46_;
	GDateTime* _tmp47_;
	GDateTime* _tmp48_;
	GDateTime* dt;
	GDateTime* _tmp49_;
	GTimeZone* _tmp50_;
	GTimeZone* _tmp51_;
	GDateTime* _tmp52_ = NULL;
	GDateTime* _tmp53_;
#line 17 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	g_return_val_if_fail (input != NULL, NULL);
#line 18 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp0_ = input;
#line 18 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	if (g_strcmp0 (_tmp0_, "") == 0) {
#line 360 "Utils.c"
		GDateTime* _tmp1_;
#line 19 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		_tmp1_ = g_date_time_new_now_local ();
#line 19 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		result = _tmp1_;
#line 19 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		return result;
#line 368 "Utils.c"
	}
#line 21 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp2_ = input;
#line 21 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp3_ = string_substring (_tmp2_, (glong) 4, (glong) 3);
#line 21 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	month_str = _tmp3_;
#line 22 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp4_ = input;
#line 22 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp5_ = string_substring (_tmp4_, (glong) 8, (glong) 2);
#line 22 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp6_ = _tmp5_;
#line 22 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp7_ = atoi (_tmp6_);
#line 22 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp8_ = _tmp7_;
#line 22 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_g_free0 (_tmp6_);
#line 22 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	day = _tmp8_;
#line 23 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp9_ = input;
#line 23 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp10_ = input;
#line 23 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp11_ = strlen (_tmp10_);
#line 23 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp12_ = _tmp11_;
#line 23 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp13_ = string_substring (_tmp9_, (glong) (_tmp12_ - 4), (glong) (-1));
#line 23 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp14_ = _tmp13_;
#line 23 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp15_ = atoi (_tmp14_);
#line 23 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp16_ = _tmp15_;
#line 23 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_g_free0 (_tmp14_);
#line 23 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	year = _tmp16_;
#line 24 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp17_ = input;
#line 24 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp18_ = string_substring (_tmp17_, (glong) 20, (glong) 5);
#line 24 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	timezone = _tmp18_;
#line 26 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	month = -1;
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp19_ = month_str;
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp20_ = _tmp19_;
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp22_ = (NULL == _tmp20_) ? 0 : g_quark_from_string (_tmp20_);
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	if (_tmp22_ == ((0 != _tmp21_label0) ? _tmp21_label0 : (_tmp21_label0 = g_quark_from_static_string ("Jan")))) {
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		switch (0) {
#line 428 "Utils.c"
			default:
			{
#line 28 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				month = 1;
#line 28 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				break;
#line 435 "Utils.c"
			}
		}
	} else if (_tmp22_ == ((0 != _tmp21_label1) ? _tmp21_label1 : (_tmp21_label1 = g_quark_from_static_string ("Feb")))) {
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		switch (0) {
#line 441 "Utils.c"
			default:
			{
#line 29 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				month = 2;
#line 29 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				break;
#line 448 "Utils.c"
			}
		}
	} else if (_tmp22_ == ((0 != _tmp21_label2) ? _tmp21_label2 : (_tmp21_label2 = g_quark_from_static_string ("Mar")))) {
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		switch (0) {
#line 454 "Utils.c"
			default:
			{
#line 30 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				month = 3;
#line 30 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				break;
#line 461 "Utils.c"
			}
		}
	} else if (_tmp22_ == ((0 != _tmp21_label3) ? _tmp21_label3 : (_tmp21_label3 = g_quark_from_static_string ("Apr")))) {
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		switch (0) {
#line 467 "Utils.c"
			default:
			{
#line 31 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				month = 4;
#line 31 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				break;
#line 474 "Utils.c"
			}
		}
	} else if (_tmp22_ == ((0 != _tmp21_label4) ? _tmp21_label4 : (_tmp21_label4 = g_quark_from_static_string ("May")))) {
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		switch (0) {
#line 480 "Utils.c"
			default:
			{
#line 32 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				month = 5;
#line 32 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				break;
#line 487 "Utils.c"
			}
		}
	} else if (_tmp22_ == ((0 != _tmp21_label5) ? _tmp21_label5 : (_tmp21_label5 = g_quark_from_static_string ("Jun")))) {
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		switch (0) {
#line 493 "Utils.c"
			default:
			{
#line 33 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				month = 6;
#line 33 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				break;
#line 500 "Utils.c"
			}
		}
	} else if (_tmp22_ == ((0 != _tmp21_label6) ? _tmp21_label6 : (_tmp21_label6 = g_quark_from_static_string ("Jul")))) {
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		switch (0) {
#line 506 "Utils.c"
			default:
			{
#line 34 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				month = 7;
#line 34 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				break;
#line 513 "Utils.c"
			}
		}
	} else if (_tmp22_ == ((0 != _tmp21_label7) ? _tmp21_label7 : (_tmp21_label7 = g_quark_from_static_string ("Aug")))) {
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		switch (0) {
#line 519 "Utils.c"
			default:
			{
#line 35 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				month = 8;
#line 35 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				break;
#line 526 "Utils.c"
			}
		}
	} else if (_tmp22_ == ((0 != _tmp21_label8) ? _tmp21_label8 : (_tmp21_label8 = g_quark_from_static_string ("Sep")))) {
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		switch (0) {
#line 532 "Utils.c"
			default:
			{
#line 36 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				month = 9;
#line 36 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				break;
#line 539 "Utils.c"
			}
		}
	} else if (_tmp22_ == ((0 != _tmp21_label9) ? _tmp21_label9 : (_tmp21_label9 = g_quark_from_static_string ("Oct")))) {
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		switch (0) {
#line 545 "Utils.c"
			default:
			{
#line 37 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				month = 10;
#line 37 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				break;
#line 552 "Utils.c"
			}
		}
	} else if (_tmp22_ == ((0 != _tmp21_label10) ? _tmp21_label10 : (_tmp21_label10 = g_quark_from_static_string ("Nov")))) {
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		switch (0) {
#line 558 "Utils.c"
			default:
			{
#line 38 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				month = 11;
#line 38 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				break;
#line 565 "Utils.c"
			}
		}
	} else if (_tmp22_ == ((0 != _tmp21_label11) ? _tmp21_label11 : (_tmp21_label11 = g_quark_from_static_string ("Dec")))) {
#line 27 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		switch (0) {
#line 571 "Utils.c"
			default:
			{
#line 39 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				month = 12;
#line 39 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
				break;
#line 578 "Utils.c"
			}
		}
	}
#line 42 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp23_ = input;
#line 42 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp24_ = string_substring (_tmp23_, (glong) 11, (glong) 2);
#line 42 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp25_ = _tmp24_;
#line 42 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp26_ = atoi (_tmp25_);
#line 42 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp27_ = _tmp26_;
#line 42 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_g_free0 (_tmp25_);
#line 42 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	hour = _tmp27_;
#line 43 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp28_ = input;
#line 43 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp29_ = string_substring (_tmp28_, (glong) 14, (glong) 2);
#line 43 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp30_ = _tmp29_;
#line 43 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp31_ = atoi (_tmp30_);
#line 43 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp32_ = _tmp31_;
#line 43 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_g_free0 (_tmp30_);
#line 43 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	minute = _tmp32_;
#line 44 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp33_ = input;
#line 44 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp34_ = string_substring (_tmp33_, (glong) 17, (glong) 2);
#line 44 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp35_ = _tmp34_;
#line 44 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp36_ = atoi (_tmp35_);
#line 44 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp37_ = _tmp36_;
#line 44 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_g_free0 (_tmp35_);
#line 44 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	second = _tmp37_;
#line 45 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp38_ = timezone;
#line 45 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp39_ = g_time_zone_new (_tmp38_);
#line 45 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp40_ = _tmp39_;
#line 45 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp41_ = year;
#line 45 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp42_ = month;
#line 45 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp43_ = day;
#line 45 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp44_ = hour;
#line 45 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp45_ = minute;
#line 45 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp46_ = second;
#line 45 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp47_ = g_date_time_new (_tmp40_, _tmp41_, _tmp42_, _tmp43_, _tmp44_, _tmp45_, (gdouble) _tmp46_);
#line 45 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp48_ = _tmp47_;
#line 45 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_g_time_zone_unref0 (_tmp40_);
#line 45 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	dt = _tmp48_;
#line 47 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp49_ = dt;
#line 47 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp50_ = g_time_zone_new_local ();
#line 47 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp51_ = _tmp50_;
#line 47 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp52_ = g_date_time_to_timezone (_tmp49_, _tmp51_);
#line 47 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp53_ = _tmp52_;
#line 47 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_g_time_zone_unref0 (_tmp51_);
#line 47 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	result = _tmp53_;
#line 47 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_g_date_time_unref0 (dt);
#line 47 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_g_free0 (timezone);
#line 47 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_g_free0 (month_str);
#line 47 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	return result;
#line 672 "Utils.c"
}


/**
 * Calculates an easily human-readable version of the time difference between 
 * time and now.
 * Example: "5m" or "3h" or "26m" or "16 Nov"
 */
gchar* utils_get_time_delta (GDateTime* time, GDateTime* now) {
	gchar* result = NULL;
	GDateTime* _tmp0_;
	GDateTime* _tmp1_;
	GTimeSpan _tmp2_ = 0LL;
	GTimeSpan diff;
	GTimeSpan _tmp3_;
	gint minutes;
	gint _tmp4_;
	gint _tmp7_;
	gint hours;
	gint _tmp8_;
	GDateTime* _tmp11_;
	gint _tmp12_ = 0;
	gchar** _tmp13_;
	gint _tmp13__length1;
	GDateTime* _tmp14_;
	gint _tmp15_ = 0;
	const gchar* _tmp16_;
	gchar* _tmp17_ = NULL;
#line 55 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	g_return_val_if_fail (time != NULL, NULL);
#line 55 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	g_return_val_if_fail (now != NULL, NULL);
#line 57 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp0_ = now;
#line 57 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp1_ = time;
#line 57 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp2_ = g_date_time_difference (_tmp0_, _tmp1_);
#line 57 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	diff = _tmp2_;
#line 59 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp3_ = diff;
#line 59 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	minutes = (gint) (((_tmp3_ / 1000.0) / 1000.0) / 60.0);
#line 60 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp4_ = minutes;
#line 60 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	if (_tmp4_ < 60) {
#line 721 "Utils.c"
		gint _tmp5_;
		gchar* _tmp6_ = NULL;
#line 61 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		_tmp5_ = minutes;
#line 61 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		_tmp6_ = g_strdup_printf ("%dm", _tmp5_);
#line 61 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		result = _tmp6_;
#line 61 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		return result;
#line 732 "Utils.c"
	}
#line 63 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp7_ = minutes;
#line 63 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	hours = (gint) (_tmp7_ / 60.0);
#line 64 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp8_ = hours;
#line 64 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	if (_tmp8_ < 24) {
#line 742 "Utils.c"
		gint _tmp9_;
		gchar* _tmp10_ = NULL;
#line 65 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		_tmp9_ = hours;
#line 65 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		_tmp10_ = g_strdup_printf ("%dh", _tmp9_);
#line 65 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		result = _tmp10_;
#line 65 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		return result;
#line 753 "Utils.c"
	}
#line 68 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp11_ = time;
#line 68 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp12_ = g_date_time_get_day_of_month (_tmp11_);
#line 68 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp13_ = utils_MONTHS;
#line 68 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp13__length1 = utils_MONTHS_length1;
#line 68 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp14_ = time;
#line 68 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp15_ = g_date_time_get_month (_tmp14_);
#line 68 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp16_ = _tmp13_[_tmp15_ - 1];
#line 68 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp17_ = g_strdup_printf ("%d %s", _tmp12_, _tmp16_);
#line 68 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	result = _tmp17_;
#line 68 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	return result;
#line 775 "Utils.c"
}


/**
 * Extracts the actual filename out of a given path.
 * E.g. for /home/foo/bar.png, it will return "bar.png"
 *
 * @return The filename of the given path, and nothing else.
 */
static gint string_last_index_of (const gchar* self, const gchar* needle, gint start_index) {
	gint result = 0;
	gint _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* _result_;
	gchar* _tmp3_;
#line 898 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, 0);
#line 898 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	g_return_val_if_fail (needle != NULL, 0);
#line 899 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	_tmp0_ = start_index;
#line 899 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	_tmp1_ = needle;
#line 899 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	_tmp2_ = g_strrstr (((gchar*) self) + _tmp0_, (gchar*) _tmp1_);
#line 899 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	_result_ = _tmp2_;
#line 901 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	_tmp3_ = _result_;
#line 901 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
	if (_tmp3_ != NULL) {
#line 808 "Utils.c"
		gchar* _tmp4_;
#line 902 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		_tmp4_ = _result_;
#line 902 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		result = (gint) (_tmp4_ - ((gchar*) self));
#line 902 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		return result;
#line 816 "Utils.c"
	} else {
#line 904 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		result = -1;
#line 904 "/usr/share/vala-0.18/vapi/glib-2.0.vapi"
		return result;
#line 822 "Utils.c"
	}
}


gchar* utils_get_file_name (const gchar* path) {
	gchar* result = NULL;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gint _tmp2_ = 0;
	gchar* _tmp3_ = NULL;
#line 78 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	g_return_val_if_fail (path != NULL, NULL);
#line 79 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp0_ = path;
#line 79 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp1_ = path;
#line 79 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp2_ = string_last_index_of (_tmp1_, "/", 0);
#line 79 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp3_ = string_substring (_tmp0_, (glong) (_tmp2_ + 1), (glong) (-1));
#line 79 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	result = _tmp3_;
#line 79 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	return result;
#line 847 "Utils.c"
}


/**
 * Extracts the file type from the given path.
 * E.g. for http://foo.org/bar/bla.png, this will just return "png"
 */
gchar* utils_get_file_type (const gchar* path) {
	gchar* result = NULL;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gint _tmp2_ = 0;
	gchar* _tmp3_ = NULL;
#line 86 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	g_return_val_if_fail (path != NULL, NULL);
#line 87 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp0_ = path;
#line 87 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp1_ = path;
#line 87 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp2_ = string_last_index_of (_tmp1_, ".", 0);
#line 87 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp3_ = string_substring (_tmp0_, (glong) (_tmp2_ + 1), (glong) (-1));
#line 87 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	result = _tmp3_;
#line 87 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	return result;
#line 875 "Utils.c"
}


/**
 * Returns the avatar name for the given path
 *
 * @return the 'calculated' avatar name
 */
gchar* utils_get_avatar_name (const gchar* path) {
	gchar* result = NULL;
	const gchar* _tmp0_;
	gchar** _tmp1_;
	gchar** _tmp2_ = NULL;
	gchar** parts;
	gint parts_length1;
	gint _parts_size_;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	const gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
#line 95 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	g_return_val_if_fail (path != NULL, NULL);
#line 96 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp0_ = path;
#line 96 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp2_ = _tmp1_ = g_strsplit (_tmp0_, "/", 0);
#line 96 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	parts = _tmp2_;
#line 96 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	parts_length1 = _vala_array_length (_tmp1_);
#line 96 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_parts_size_ = parts_length1;
#line 97 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp3_ = parts[parts_length1 - 2];
#line 97 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp4_ = g_strconcat (_tmp3_, "_", NULL);
#line 97 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp5_ = _tmp4_;
#line 97 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp6_ = parts[parts_length1 - 1];
#line 97 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp7_ = g_strconcat (_tmp5_, _tmp6_, NULL);
#line 97 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp8_ = _tmp7_;
#line 97 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_g_free0 (_tmp5_);
#line 97 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	result = _tmp8_;
#line 97 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
#line 97 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	return result;
#line 930 "Utils.c"
}


/**
 * Shows an error dialog with the given error message
 */
static Block18Data* block18_data_ref (Block18Data* _data18_) {
#line 104 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	g_atomic_int_inc (&_data18_->_ref_count_);
#line 104 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	return _data18_;
#line 942 "Utils.c"
}


static void block18_data_unref (void * _userdata_) {
	Block18Data* _data18_;
	_data18_ = (Block18Data*) _userdata_;
#line 104 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	if (g_atomic_int_dec_and_test (&_data18_->_ref_count_)) {
#line 104 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		_g_object_unref0 (_data18_->dialog);
#line 104 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		g_slice_free (Block18Data, _data18_);
#line 955 "Utils.c"
	}
}


static void __lambda8_ (Block18Data* _data18_, gint id) {
	gint _tmp0_;
#line 110 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp0_ = id;
#line 110 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	if (_tmp0_ == ((gint) GTK_RESPONSE_OK)) {
#line 111 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		gtk_widget_destroy (G_TYPE_CHECK_INSTANCE_CAST (_data18_->dialog, GTK_TYPE_WIDGET, GtkWidget));
#line 968 "Utils.c"
	}
}


static void ___lambda8__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
#line 109 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	__lambda8_ (self, response_id);
#line 976 "Utils.c"
}


void utils_show_error_dialog (const gchar* message) {
	Block18Data* _data18_;
	const gchar* _tmp0_;
	GtkMessageDialog* _tmp1_;
#line 104 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	g_return_if_fail (message != NULL);
#line 104 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_data18_ = g_slice_new0 (Block18Data);
#line 104 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_data18_->_ref_count_ = 1;
#line 105 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp0_ = message;
#line 105 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp1_ = (GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_DESTROY_WITH_PARENT, GTK_MESSAGE_ERROR, GTK_BUTTONS_OK, _tmp0_);
#line 105 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	g_object_ref_sink (_tmp1_);
#line 105 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_data18_->dialog = _tmp1_;
#line 109 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	g_signal_connect_data (G_TYPE_CHECK_INSTANCE_CAST (_data18_->dialog, GTK_TYPE_DIALOG, GtkDialog), "response", (GCallback) ___lambda8__gtk_dialog_response, block18_data_ref (_data18_), (GClosureNotify) block18_data_unref, 0);
#line 114 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	gtk_widget_show (G_TYPE_CHECK_INSTANCE_CAST (_data18_->dialog, GTK_TYPE_WIDGET, GtkWidget));
#line 104 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	block18_data_unref (_data18_);
#line 104 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_data18_ = NULL;
#line 1006 "Utils.c"
}


Utils* utils_construct (GType object_type) {
	Utils* self = NULL;
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	self = (Utils*) g_type_create_instance (object_type);
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	return self;
#line 1016 "Utils.c"
}


Utils* utils_new (void) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	return utils_construct (TYPE_UTILS);
#line 1023 "Utils.c"
}


static void value_utils_init (GValue* value) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	value->data[0].v_pointer = NULL;
#line 1030 "Utils.c"
}


static void value_utils_free_value (GValue* value) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	if (value->data[0].v_pointer) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		utils_unref (value->data[0].v_pointer);
#line 1039 "Utils.c"
	}
}


static void value_utils_copy_value (const GValue* src_value, GValue* dest_value) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	if (src_value->data[0].v_pointer) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		dest_value->data[0].v_pointer = utils_ref (src_value->data[0].v_pointer);
#line 1049 "Utils.c"
	} else {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		dest_value->data[0].v_pointer = NULL;
#line 1053 "Utils.c"
	}
}


static gpointer value_utils_peek_pointer (const GValue* value) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	return value->data[0].v_pointer;
#line 1061 "Utils.c"
}


static gchar* value_utils_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	if (collect_values[0].v_pointer) {
#line 1068 "Utils.c"
		Utils* object;
		object = collect_values[0].v_pointer;
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		if (object->parent_instance.g_class == NULL) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 1075 "Utils.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 1079 "Utils.c"
		}
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		value->data[0].v_pointer = utils_ref (object);
#line 1083 "Utils.c"
	} else {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		value->data[0].v_pointer = NULL;
#line 1087 "Utils.c"
	}
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	return NULL;
#line 1091 "Utils.c"
}


static gchar* value_utils_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	Utils** object_p;
	object_p = collect_values[0].v_pointer;
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	if (!object_p) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 1102 "Utils.c"
	}
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	if (!value->data[0].v_pointer) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		*object_p = NULL;
#line 1108 "Utils.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		*object_p = value->data[0].v_pointer;
#line 1112 "Utils.c"
	} else {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		*object_p = utils_ref (value->data[0].v_pointer);
#line 1116 "Utils.c"
	}
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	return NULL;
#line 1120 "Utils.c"
}


GParamSpec* param_spec_utils (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecUtils* spec;
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_UTILS), NULL);
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	return G_PARAM_SPEC (spec);
#line 1134 "Utils.c"
}


gpointer value_get_utils (const GValue* value) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_UTILS), NULL);
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	return value->data[0].v_pointer;
#line 1143 "Utils.c"
}


void value_set_utils (GValue* value, gpointer v_object) {
	Utils* old;
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_UTILS));
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	old = value->data[0].v_pointer;
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	if (v_object) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_UTILS));
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		value->data[0].v_pointer = v_object;
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		utils_ref (value->data[0].v_pointer);
#line 1163 "Utils.c"
	} else {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		value->data[0].v_pointer = NULL;
#line 1167 "Utils.c"
	}
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	if (old) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		utils_unref (old);
#line 1173 "Utils.c"
	}
}


void value_take_utils (GValue* value, gpointer v_object) {
	Utils* old;
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_UTILS));
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	old = value->data[0].v_pointer;
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	if (v_object) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_UTILS));
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		value->data[0].v_pointer = v_object;
#line 1192 "Utils.c"
	} else {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		value->data[0].v_pointer = NULL;
#line 1196 "Utils.c"
	}
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	if (old) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		utils_unref (old);
#line 1202 "Utils.c"
	}
}


static void utils_class_init (UtilsClass * klass) {
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar** _tmp12_ = NULL;
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	utils_parent_class = g_type_class_peek_parent (klass);
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	UTILS_CLASS (klass)->finalize = utils_finalize;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp0_ = g_strdup ("Jan");
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp1_ = g_strdup ("Feb");
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp2_ = g_strdup ("Mar");
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp3_ = g_strdup ("Apr");
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp4_ = g_strdup ("May");
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp5_ = g_strdup ("Jun");
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp6_ = g_strdup ("Jul");
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp7_ = g_strdup ("Aug");
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp8_ = g_strdup ("Sep");
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp9_ = g_strdup ("Oct");
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp10_ = g_strdup ("Nov");
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp11_ = g_strdup ("Dec");
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp12_ = g_new0 (gchar*, 12 + 1);
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp12_[0] = _tmp0_;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp12_[1] = _tmp1_;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp12_[2] = _tmp2_;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp12_[3] = _tmp3_;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp12_[4] = _tmp4_;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp12_[5] = _tmp5_;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp12_[6] = _tmp6_;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp12_[7] = _tmp7_;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp12_[8] = _tmp8_;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp12_[9] = _tmp9_;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp12_[10] = _tmp10_;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	_tmp12_[11] = _tmp11_;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	utils_MONTHS = _tmp12_;
#line 6 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	utils_MONTHS_length1 = 12;
#line 1279 "Utils.c"
}


static void utils_instance_init (Utils * self) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	self->ref_count = 1;
#line 1286 "Utils.c"
}


static void utils_finalize (Utils* obj) {
	Utils * self;
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_UTILS, Utils);
#line 1294 "Utils.c"
}


GType utils_get_type (void) {
	static volatile gsize utils_type_id__volatile = 0;
	if (g_once_init_enter (&utils_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_utils_init, value_utils_free_value, value_utils_copy_value, value_utils_peek_pointer, "p", value_utils_collect_value, "p", value_utils_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (UtilsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) utils_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Utils), 0, (GInstanceInitFunc) utils_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType utils_type_id;
		utils_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Utils", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&utils_type_id__volatile, utils_type_id);
	}
	return utils_type_id__volatile;
}


gpointer utils_ref (gpointer instance) {
	Utils* self;
	self = instance;
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	g_atomic_int_inc (&self->ref_count);
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	return instance;
#line 1319 "Utils.c"
}


void utils_unref (gpointer instance) {
	Utils* self;
	self = instance;
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		UTILS_GET_CLASS (self)->finalize (self);
#line 5 "/home/baedert/Code/Vala/Corebird/src/util/Utils.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 1332 "Utils.c"
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



