.TH "corebird" "1" "08. Feb. 2014" "man page by Malcolm J Lewis" ""
.SH NAME
.B
corebird
- Native Gtk+ Twitter client for the Linux desktop.

.SH SYNOPSIS
.B
corebird [--tweet=@screen_name]

.SH DESCRIPTION
- Corebird is a native GTK+ twitter client that provides vital features such as Direct Messages (DMs), tweet notifications, conversation views.

- Additional features include the ability to change to the GTK+ dark theme, searching and media uploads.

.SH KEYBOARD SHORTCUTS [command]
.B
[Ctrl + t] -
Compose tweet

.B
[Back] -
Go one page back (this can be triggered via the back button on the keyboard, the back thumb button on the mouse or [Alt + Left])

.B
[Forward] -
Go one page forward(this can be triggered via the forward button on the keyboard, the forward thumb button on the mouse or [Alt + Right])

.B
[Alt + num] -
Go to page [num] (between 1 and 5 at the moment)

.B
[Ctrl + Shift + s] -
Show/Hide sidebar

.B
When a tweet is focused (via keynav)

.B
[r] -
Reply

.B
[tt] -
Retweet

.B
[f] -
Favorite

.B
[dd] -
Delete

.B
[Return] -
Show tweet details

.SH AUTHOR
Written by Timm Bäder.

.SH HOMEPAGE
https://corebird.baedert.org/

.SH REPORTING BUGS
https://github.com/baedert/corebird/issues
